#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : R-pkgdown
Version  : 1.3.0
Release  : 1
URL      : https://cran.r-project.org/src/contrib/pkgdown_1.3.0.tar.gz
Source0  : https://cran.r-project.org/src/contrib/pkgdown_1.3.0.tar.gz
Summary  : Make Static HTML Documentation for a Package
Group    : Development/Tools
License  : MIT
Requires: R-callr
Requires: R-desc
Requires: R-devtools
Requires: R-fs
Requires: R-highlight
Requires: R-memoise
Requires: R-rematch2
Requires: R-rmarkdown
Requires: R-roxygen2
Requires: R-rsconnect
Requires: R-rstudioapi
Requires: R-tibble
Requires: R-usethis
Requires: R-whisker
Requires: R-withr
Requires: R-xml2
BuildRequires : R-callr
BuildRequires : R-desc
BuildRequires : R-devtools
BuildRequires : R-fs
BuildRequires : R-highlight
BuildRequires : R-memoise
BuildRequires : R-rematch2
BuildRequires : R-rmarkdown
BuildRequires : R-roxygen2
BuildRequires : R-rsconnect
BuildRequires : R-rstudioapi
BuildRequires : R-tibble
BuildRequires : R-usethis
BuildRequires : R-whisker
BuildRequires : R-withr
BuildRequires : R-xml2
BuildRequires : buildreq-R

%description
# pkgdown <img src="man/figures/logo.png" align="right" alt="" width="120" />
[![Travis-CI build
status](https://travis-ci.org/r-lib/pkgdown.svg?branch=master)](https://travis-ci.org/r-lib/pkgdown)
[![AppVeyor build
status](https://ci.appveyor.com/api/projects/status/github/r-lib/pkgdown?branch=master&svg=true)](https://ci.appveyor.com/project/r-lib/pkgdown)
[![Lifecycle:
maturing](https://img.shields.io/badge/lifecycle-maturing-blue.svg)](https://www.tidyverse.org/lifecycle/#maturing)
[![CRAN
Status](https://www.r-pkg.org/badges/version/pkgdown)](https://cran.r-project.org/package=pkgdown)
[![Codecov test
coverage](https://img.shields.io/codecov/c/github/r-lib/pkgdown/master.svg)](https://codecov.io/github/r-lib/pkgdown?branch=master)

%prep
%setup -q -c -n pkgdown

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1549279182

%install
export SOURCE_DATE_EPOCH=1549279182
rm -rf %{buildroot}
export LANG=C
export CFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FCFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -O3 -flto -fno-semantic-interposition "
export AR=gcc-ar
export RANLIB=gcc-ranlib
export LDFLAGS="$LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library

mkdir -p ~/.R
mkdir -p ~/.stash
echo "CFLAGS = $CFLAGS -march=haswell -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=haswell -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=haswell -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library pkgdown
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx2 ; mv $i.avx2 ~/.stash/; done
echo "CFLAGS = $CFLAGS -march=skylake-avx512 -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=skylake-avx512 -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=skylake-avx512 -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --no-test-load --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library pkgdown
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx512 ; mv $i.avx512 ~/.stash/; done
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library pkgdown
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc -l %{buildroot}/usr/lib64/R/library pkgdown|| : 
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :


%files
%defattr(-,root,root,-)
/usr/lib64/R/library/pkgdown/DESCRIPTION
/usr/lib64/R/library/pkgdown/INDEX
/usr/lib64/R/library/pkgdown/LICENSE
/usr/lib64/R/library/pkgdown/Meta/Rd.rds
/usr/lib64/R/library/pkgdown/Meta/features.rds
/usr/lib64/R/library/pkgdown/Meta/hsearch.rds
/usr/lib64/R/library/pkgdown/Meta/links.rds
/usr/lib64/R/library/pkgdown/Meta/nsInfo.rds
/usr/lib64/R/library/pkgdown/Meta/package.rds
/usr/lib64/R/library/pkgdown/Meta/vignette.rds
/usr/lib64/R/library/pkgdown/NAMESPACE
/usr/lib64/R/library/pkgdown/NEWS.md
/usr/lib64/R/library/pkgdown/R/pkgdown
/usr/lib64/R/library/pkgdown/R/pkgdown.rdb
/usr/lib64/R/library/pkgdown/R/pkgdown.rdx
/usr/lib64/R/library/pkgdown/assets/docsearch.css
/usr/lib64/R/library/pkgdown/assets/docsearch.js
/usr/lib64/R/library/pkgdown/assets/link.svg
/usr/lib64/R/library/pkgdown/assets/pkgdown.css
/usr/lib64/R/library/pkgdown/assets/pkgdown.js
/usr/lib64/R/library/pkgdown/doc/index.html
/usr/lib64/R/library/pkgdown/doc/pkgdown.Rmd
/usr/lib64/R/library/pkgdown/doc/pkgdown.html
/usr/lib64/R/library/pkgdown/help/AnIndex
/usr/lib64/R/library/pkgdown/help/aliases.rds
/usr/lib64/R/library/pkgdown/help/figures/bacon.jpg
/usr/lib64/R/library/pkgdown/help/figures/logo.png
/usr/lib64/R/library/pkgdown/help/paths.rds
/usr/lib64/R/library/pkgdown/help/pkgdown.rdb
/usr/lib64/R/library/pkgdown/help/pkgdown.rdx
/usr/lib64/R/library/pkgdown/html/00Index.html
/usr/lib64/R/library/pkgdown/html/R.css
/usr/lib64/R/library/pkgdown/rstudio/addins.dcf
/usr/lib64/R/library/pkgdown/templates/config-docsearch.json
/usr/lib64/R/library/pkgdown/templates/content-article-index.html
/usr/lib64/R/library/pkgdown/templates/content-article.html
/usr/lib64/R/library/pkgdown/templates/content-authors.html
/usr/lib64/R/library/pkgdown/templates/content-citation-authors.html
/usr/lib64/R/library/pkgdown/templates/content-home.html
/usr/lib64/R/library/pkgdown/templates/content-news-index.html
/usr/lib64/R/library/pkgdown/templates/content-news.html
/usr/lib64/R/library/pkgdown/templates/content-reference-index.html
/usr/lib64/R/library/pkgdown/templates/content-reference-topic.html
/usr/lib64/R/library/pkgdown/templates/content-title-body.html
/usr/lib64/R/library/pkgdown/templates/content-tutorial-index.html
/usr/lib64/R/library/pkgdown/templates/content-tutorial.html
/usr/lib64/R/library/pkgdown/templates/docsearch.html
/usr/lib64/R/library/pkgdown/templates/footer.html
/usr/lib64/R/library/pkgdown/templates/head.html
/usr/lib64/R/library/pkgdown/templates/header.html
/usr/lib64/R/library/pkgdown/templates/layout.html
/usr/lib64/R/library/pkgdown/templates/navbar.html
